//! Replanning system for automatic plan adjustment
//!
//! This module provides automatic replanning capabilities when tasks
//! fail, get blocked, or when the plan becomes stale.

use serde::{Deserialize, Serialize};
use std::sync::Arc;

use crate::tasks::{Task, TaskStatus};
use echo_core::llm::LlmClient;

/// Replanning trigger condition
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReplanTrigger {
    /// Task failed
    TaskFailure { task_id: String, error: String },
    /// Task blocked
    TaskBlocked { task_id: String, reason: String },
    /// Plan became stale (e.g., external changes)
    PlanStale { reason: String },
    /// Context pressure (approaching token limit)
    ContextPressure { usage_percent: f32 },
    /// Deadline approaching
    DeadlineApproaching { remaining_percent: f32 },
}

/// Replanning decision
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReplanDecision {
    /// Continue with current plan
    Continue,
    /// Replan with new strategy
    Replan { reason: String, new_plan: String },
    /// Abort execution
    Abort { reason: String },
}

/// Replanner trait for automatic plan adjustment
pub trait Replanner: Send + Sync {
    /// Check if replanning is needed
    fn should_replan(&self, trigger: &ReplanTrigger) -> ReplanDecision;

    /// Generate a new plan based on the trigger
    fn replan(
        &self,
        trigger: &ReplanTrigger,
        current_plan: &str,
        tasks: &[Task],
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<String, String>> + Send + '_>>;
}

/// LLM-based replanner
pub struct LlmReplanner {
    llm_client: Arc<dyn LlmClient>,
    max_replan_attempts: u32,
    replan_attempts: std::sync::atomic::AtomicU32,
}

impl LlmReplanner {
    /// Create a new LLM-based replanner
    pub fn new(llm_client: Arc<dyn LlmClient>, max_replan_attempts: u32) -> Self {
        Self {
            llm_client,
            max_replan_attempts,
            replan_attempts: std::sync::atomic::AtomicU32::new(0),
        }
    }

    /// Get current replan attempt count
    pub fn replan_attempts(&self) -> u32 {
        self.replan_attempts
            .load(std::sync::atomic::Ordering::SeqCst)
    }

    /// Reset replan attempt counter
    pub fn reset_attempts(&self) {
        self.replan_attempts
            .store(0, std::sync::atomic::Ordering::SeqCst);
    }
}

impl Replanner for LlmReplanner {
    fn should_replan(&self, trigger: &ReplanTrigger) -> ReplanDecision {
        let attempts = self.replan_attempts();

        if attempts >= self.max_replan_attempts {
            return ReplanDecision::Abort {
                reason: format!("Max replan attempts ({}) reached", self.max_replan_attempts),
            };
        }

        match trigger {
            ReplanTrigger::TaskFailure { task_id, error } => {
                ReplanDecision::Replan {
                    reason: format!("Task {} failed: {}", task_id, error),
                    new_plan: String::new(), // Will be generated by replan()
                }
            }
            ReplanTrigger::TaskBlocked { task_id, reason } => ReplanDecision::Replan {
                reason: format!("Task {} blocked: {}", task_id, reason),
                new_plan: String::new(),
            },
            ReplanTrigger::PlanStale { reason } => ReplanDecision::Replan {
                reason: format!("Plan became stale: {}", reason),
                new_plan: String::new(),
            },
            ReplanTrigger::ContextPressure { usage_percent } => {
                if *usage_percent > 0.8 {
                    ReplanDecision::Replan {
                        reason: format!("Context pressure high: {:.1}%", usage_percent * 100.0),
                        new_plan: String::new(),
                    }
                } else {
                    ReplanDecision::Continue
                }
            }
            ReplanTrigger::DeadlineApproaching { remaining_percent } => {
                if *remaining_percent < 0.2 {
                    ReplanDecision::Replan {
                        reason: format!(
                            "Deadline approaching: {:.1}% remaining",
                            remaining_percent * 100.0
                        ),
                        new_plan: String::new(),
                    }
                } else {
                    ReplanDecision::Continue
                }
            }
        }
    }

    fn replan(
        &self,
        trigger: &ReplanTrigger,
        current_plan: &str,
        tasks: &[Task],
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<String, String>> + Send>> {
        let llm_client = self.llm_client.clone();
        let trigger = trigger.clone();
        let current_plan = current_plan.to_string();
        let tasks = tasks.to_vec();
        let replan_attempts = self
            .replan_attempts
            .fetch_add(1, std::sync::atomic::Ordering::SeqCst);

        Box::pin(async move {
            // Build task summary
            let task_summary: Vec<String> = tasks
                .iter()
                .map(|t| {
                    format!(
                        "- {} ({}): {}",
                        t.id,
                        match t.status {
                            TaskStatus::Pending => "pending",
                            TaskStatus::InProgress => "in_progress",
                            TaskStatus::Completed => "completed",
                            TaskStatus::Failed(_) => "failed",
                            TaskStatus::Blocked(_) => "blocked",
                            TaskStatus::Cancelled => "cancelled",
                            TaskStatus::TimedOut { .. } => "timed_out",
                            TaskStatus::Retrying { .. } => "retrying",
                        },
                        t.description
                    )
                })
                .collect();

            let trigger_description = match &trigger {
                ReplanTrigger::TaskFailure { task_id, error } => {
                    format!("Task {} failed with error: {}", task_id, error)
                }
                ReplanTrigger::TaskBlocked { task_id, reason } => {
                    format!("Task {} blocked: {}", task_id, reason)
                }
                ReplanTrigger::PlanStale { reason } => {
                    format!("Plan became stale: {}", reason)
                }
                ReplanTrigger::ContextPressure { usage_percent } => {
                    format!("Context pressure high: {:.1}%", usage_percent * 100.0)
                }
                ReplanTrigger::DeadlineApproaching { remaining_percent } => {
                    format!(
                        "Deadline approaching: {:.1}% remaining",
                        remaining_percent * 100.0
                    )
                }
            };

            let prompt = format!(
                r#"You are a task replanner. The current plan needs adjustment due to:

{}

Current plan:
{}

Current tasks:
{}

Generate a new plan that addresses the issue and continues towards the goal.
Focus on:
1. Addressing the failure/blockage
2. Maintaining progress towards the goal
3. Being realistic about what can be achieved

Output only the new plan, no explanations."#,
                trigger_description,
                current_plan,
                task_summary.join("\n")
            );

            let response = llm_client
                .chat_simple(vec![echo_core::llm::Message::user(prompt)])
                .await
                .map_err(|e| format!("Failed to generate new plan: {}", e))?;

            Ok(response)
        })
    }
}

/// Simple rule-based replanner
pub struct RuleBasedReplanner {
    max_replan_attempts: u32,
    replan_attempts: std::sync::atomic::AtomicU32,
}

impl RuleBasedReplanner {
    /// Create a new rule-based replanner
    pub fn new(max_replan_attempts: u32) -> Self {
        Self {
            max_replan_attempts,
            replan_attempts: std::sync::atomic::AtomicU32::new(0),
        }
    }

    /// Get current replan attempt count
    pub fn replan_attempts(&self) -> u32 {
        self.replan_attempts
            .load(std::sync::atomic::Ordering::SeqCst)
    }

    /// Reset replan attempt counter
    pub fn reset_attempts(&self) {
        self.replan_attempts
            .store(0, std::sync::atomic::Ordering::SeqCst);
    }
}

impl Replanner for RuleBasedReplanner {
    fn should_replan(&self, trigger: &ReplanTrigger) -> ReplanDecision {
        let attempts = self.replan_attempts();

        if attempts >= self.max_replan_attempts {
            return ReplanDecision::Abort {
                reason: format!("Max replan attempts ({}) reached", self.max_replan_attempts),
            };
        }

        match trigger {
            ReplanTrigger::TaskFailure { task_id, error } => {
                // Simple rule: retry once, then abort
                if attempts == 0 {
                    ReplanDecision::Replan {
                        reason: format!("Task {} failed: {}, retrying", task_id, error),
                        new_plan: format!("Retry task {} with adjusted parameters", task_id),
                    }
                } else {
                    ReplanDecision::Abort {
                        reason: format!("Task {} failed after retry: {}", task_id, error),
                    }
                }
            }
            ReplanTrigger::TaskBlocked { task_id, reason } => {
                // Simple rule: skip blocked task
                ReplanDecision::Replan {
                    reason: format!("Task {} blocked: {}, skipping", task_id, reason),
                    new_plan: format!("Skip task {} and continue with remaining tasks", task_id),
                }
            }
            ReplanTrigger::PlanStale { reason } => ReplanDecision::Replan {
                reason: format!("Plan became stale: {}", reason),
                new_plan: "Regenerate plan based on current state".to_string(),
            },
            ReplanTrigger::ContextPressure { usage_percent } => {
                if *usage_percent > 0.9 {
                    ReplanDecision::Abort {
                        reason: format!("Context pressure too high: {:.1}%", usage_percent * 100.0),
                    }
                } else if *usage_percent > 0.8 {
                    ReplanDecision::Replan {
                        reason: format!("Context pressure high: {:.1}%", usage_percent * 100.0),
                        new_plan: "Compress context and continue".to_string(),
                    }
                } else {
                    ReplanDecision::Continue
                }
            }
            ReplanTrigger::DeadlineApproaching { remaining_percent } => {
                if *remaining_percent < 0.1 {
                    ReplanDecision::Abort {
                        reason: format!(
                            "Deadline too close: {:.1}% remaining",
                            remaining_percent * 100.0
                        ),
                    }
                } else if *remaining_percent < 0.3 {
                    ReplanDecision::Replan {
                        reason: format!(
                            "Deadline approaching: {:.1}% remaining",
                            remaining_percent * 100.0
                        ),
                        new_plan: "Focus on critical tasks only".to_string(),
                    }
                } else {
                    ReplanDecision::Continue
                }
            }
        }
    }

    fn replan(
        &self,
        _trigger: &ReplanTrigger,
        _current_plan: &str,
        _tasks: &[Task],
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<String, String>> + Send>> {
        let decision = self.should_replan(_trigger);
        let current_plan = _current_plan.to_string();

        Box::pin(async move {
            match decision {
                ReplanDecision::Replan { new_plan, .. } => Ok(new_plan),
                ReplanDecision::Continue => Ok(current_plan),
                ReplanDecision::Abort { reason } => Err(reason),
            }
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_replan_trigger_task_failure() {
        let trigger = ReplanTrigger::TaskFailure {
            task_id: "task1".to_string(),
            error: "error occurred".to_string(),
        };

        let replanner = RuleBasedReplanner::new(3);
        let decision = replanner.should_replan(&trigger);

        assert!(matches!(decision, ReplanDecision::Replan { .. }));
    }

    #[test]
    fn test_replan_trigger_task_blocked() {
        let trigger = ReplanTrigger::TaskBlocked {
            task_id: "task1".to_string(),
            reason: "waiting for input".to_string(),
        };

        let replanner = RuleBasedReplanner::new(3);
        let decision = replanner.should_replan(&trigger);

        assert!(matches!(decision, ReplanDecision::Replan { .. }));
    }

    #[test]
    fn test_replan_trigger_context_pressure() {
        let trigger = ReplanTrigger::ContextPressure {
            usage_percent: 0.85,
        };

        let replanner = RuleBasedReplanner::new(3);
        let decision = replanner.should_replan(&trigger);

        assert!(matches!(decision, ReplanDecision::Replan { .. }));
    }

    #[test]
    fn test_replan_trigger_context_pressure_low() {
        let trigger = ReplanTrigger::ContextPressure { usage_percent: 0.5 };

        let replanner = RuleBasedReplanner::new(3);
        let decision = replanner.should_replan(&trigger);

        assert_eq!(decision, ReplanDecision::Continue);
    }

    #[test]
    fn test_replan_trigger_deadline_approaching() {
        let trigger = ReplanTrigger::DeadlineApproaching {
            remaining_percent: 0.15,
        };

        let replanner = RuleBasedReplanner::new(3);
        let decision = replanner.should_replan(&trigger);

        assert!(matches!(decision, ReplanDecision::Replan { .. }));
    }

    #[test]
    fn test_replan_trigger_deadline_safe() {
        let trigger = ReplanTrigger::DeadlineApproaching {
            remaining_percent: 0.5,
        };

        let replanner = RuleBasedReplanner::new(3);
        let decision = replanner.should_replan(&trigger);

        assert_eq!(decision, ReplanDecision::Continue);
    }

    #[test]
    fn test_replan_max_attempts() {
        let trigger = ReplanTrigger::TaskFailure {
            task_id: "task1".to_string(),
            error: "error".to_string(),
        };

        let replanner = RuleBasedReplanner::new(2);

        // First attempt (attempts = 0) - should replan (retry once)
        let decision1 = replanner.should_replan(&trigger);
        assert!(matches!(decision1, ReplanDecision::Replan { .. }));

        // Increment attempts to 1 (simulating that replan() was called)
        replanner
            .replan_attempts
            .fetch_add(1, std::sync::atomic::Ordering::SeqCst);

        // Second attempt (attempts = 1) - should abort (already retried once)
        let decision2 = replanner.should_replan(&trigger);
        assert!(matches!(decision2, ReplanDecision::Abort { .. }));
    }

    #[test]
    fn test_replan_reset_attempts() {
        let replanner = RuleBasedReplanner::new(3);

        // Increment attempts
        replanner
            .replan_attempts
            .fetch_add(2, std::sync::atomic::Ordering::SeqCst);
        assert_eq!(replanner.replan_attempts(), 2);

        // Reset
        replanner.reset_attempts();
        assert_eq!(replanner.replan_attempts(), 0);
    }

    #[tokio::test]
    async fn test_rule_based_replanner() {
        let replanner = RuleBasedReplanner::new(3);

        let trigger = ReplanTrigger::TaskFailure {
            task_id: "task1".to_string(),
            error: "error occurred".to_string(),
        };

        let current_plan = "Original plan";
        let tasks = vec![];

        let new_plan = replanner.replan(&trigger, current_plan, &tasks).await;
        assert!(new_plan.is_ok());
        assert!(new_plan.unwrap().contains("Retry task task1"));
    }
}
